PruebaTecnicaWebAPP.UI/Models/ErrorViewModel.cs
namespace PruebaTecnicaWebAPP.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PruebaTecnicaWebAPP.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PruebaTecnicaWebAPP.UI.Models;
using System.Diagnostics;

namespace PruebaTecnicaWebAPP.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PruebaTecnicaWebAPP.UI/Controllers/SystemController.cs
using Microsoft.AspNetCore.Mvc;
using PruebaTecnicaWebAPP.Models;
using PruebaTecnicaWebAPP.Models.DTO;
using PruebaTecnicaWebAPP.Interfaces;
using PruebaTecnicaWebAPP.BussinesLogic;

namespace PruebaTecnicaWebAPP.Controllers
{
    public class SystemController : Controller
    {
        private readonly ITodoTask _todoTask;
        private readonly ILogger<SystemController> _logger;

        public SystemController(ITodoTask todoTask, ILogger<SystemController> logger)
        {
            _todoTask = todoTask;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            ResponseDto<List<TodoTask>> Response = await _todoTask.Get();
            return View(Response.Data);
        }
        // GET: SystemController/TodoTask
        [HttpGet]
        public async Task<IActionResult> TodoTask()
        {
            ResponseDto<List<TodoTask>> Response = await _todoTask.Get();
            return View(Response.Data);

        }

        // POST: SystemController/Create
        [HttpPost]
        public async Task<JsonResult> Create(TodoTask data)
        {
            var ResponseDTO = new ResponseDto<TodoTask>();
            var TodoTaskBL = new TodoTaskBL();
            ResponseDTO = await TodoTaskBL.Create(data);

            return Json(new { data = ResponseDTO });
        }

        // GET: SystemController/GetById
        public async Task<JsonResult> GetById(TodoTask data)
        {
            var ResponseDTO = new ResponseDto<TodoTask>();
            var TodoTaskBL = new TodoTaskBL();
            ResponseDTO = await TodoTaskBL.GetById(data);


            return Json(new { data = ResponseDTO });
        }

        // POST: SystemController/Edit
        [HttpPost]
        public async Task<JsonResult> Edit(TodoTask data)
        {
            var ResponseDTO = new ResponseDto<TodoTask>();
            var TodoTaskBL = new TodoTaskBL();
            ResponseDTO = await TodoTaskBL.Edit(data);

            return Json(new { data = ResponseDTO });
        }


        // POST: SystemController/Delete
        [HttpPost]
        public async Task<JsonResult> Delete(TodoTask data)
        {
            var ResponseDTO = new ResponseDto<TodoTask>();
            var TodoTaskBL = new TodoTaskBL();
            ResponseDTO = await TodoTaskBL.Delete(data);

            return Json(new { data = ResponseDTO });
        }
    }
}

PruebaTecnicaWebAPP.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PruebaTecnicaWebAPP.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PruebaTecnicaWebAPP</title>

    <!-- Custom fonts for this template-->
    <link href="~/TodoTask/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/TodoTask/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/TodoTask/sweetalert/sweetalert.css" rel="stylesheet">
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Prueba Tecnica</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="nav-link active" asp-area="" asp-controller="System" asp-action="Index" onclick="Onrecargar()">Ir al listado de tareas</a>
      
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PruebaTecnicaWebAPP.UI - <a asp-area="" asp-controller="System" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/TodoTask/jquery/jquery.min.js"></script>
    <script src="~/TodoTask/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/TodoTask/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/TodoTask/toastr/toastr.min.js"></script>
    <script src="~/TodoTask/sweetalert/sweetalert.js"></script>
    <script src="~/TodoTask/loadingoverlay/loadingoverlay.min.js"></script>
    <script src="~/TodoTask/fontawesome/js/all.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        function recargar() {
            var boton = document.getElementById('MostrarTodo');
            boton.click();
        }
    </script>
</body>
</html>